### ISSUE TITLE
error code, help me

### ISSUE THREAD

**Issue by thewind11235** [sudoguy/tiktokpy#123]
2021-01-18 15:31:30 | INFO | 🥳 TikTokPy initialized. Version: 0.8.8
2021-01-18 15:31:30 | INFO | 🔧 Settings successfully loaded
2021-01-18 15:31:30 | INFO | ✅ Used cookies of @xxxx._
Traceback (most recent call last):
  File "tiktok.py", line 37, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "tiktok.py", line 6, in main
    async with TikTokPy() as bot:
  File "/home/mingdv/tiktok/tiktokpy/tiktokpy/bot/__init__.py", line 35, in __aenter__
    await self._init_bot()
  File "/home/mingdv/tiktok/tiktokpy/tiktokpy/bot/__init__.py", line 98, in _init_bot
    self.client: Client = await Client.create()
  File "/home/mingdv/tiktok/tiktokpy/tiktokpy/client/__init__.py", line 96, in create
    self = Client()
  File "/home/mingdv/tiktok/tiktokpy/tiktokpy/client/__init__.py", line 29, in __init__
    self.cookies = json.loads(settings.get("COOKIES", "[]"))
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by vroomvroom-jpeg** [comment]
i cant help you but how did you start the program?
