### ISSUE TITLE
Project actually work? / still alive? i get a strange error

### ISSUE THREAD

**Issue by MarcoLavoro** [sudoguy/tiktokpy#135]
I installed but i get this error, is normal?

`python3 '/home/ma/Scrivania/tiktok/tiktokbot (copia).py'
2021-02-13 11:57:13 | INFO | 🥳 TikTokPy initialized. Version: 0.8.9
2021-02-13 11:57:13 | INFO | 🔧 Settings successfully loaded
2021-02-13 11:57:13 | INFO | 🛑 Cookies not found, anonymous mode
2021-02-13 11:57:13 | INFO | 📈 Getting trending items
📈 Getting trending EN:   0%|                             | 0/5 [00:00<?, ?it/s]2021-02-13 11:57:19 | INFO | ✋ TikTokPy finished working. Session lasted: 6 seconds
Traceback (most recent call last):
  File "/home/ma/Scrivania/tiktok/tiktokbot (copia).py", line 37, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/ma/Scrivania/tiktok/tiktokbot (copia).py", line 8, in main
    trending_items = await bot.trending(amount=5)
  File "/home/ma/.local/lib/python3.8/site-packages/tiktokpy/bot/__init__.py", line 57, in trending
    items = await Trending(client=self.client).feed(amount=amount, lang=lang)
  File "/home/ma/.local/lib/python3.8/site-packages/tiktokpy/client/trending.py", line 41, in feed
    await page.evaluate(
  File "/home/ma/.local/lib/python3.8/site-packages/pyppeteer/page.py", line 1184, in evaluate
    return await frame.evaluate(pageFunction, *args, force_expr=force_expr)
  File "/home/ma/.local/lib/python3.8/site-packages/pyppeteer/frame_manager.py", line 308, in evaluate
    return await context.evaluate(
  File "/home/ma/.local/lib/python3.8/site-packages/pyppeteer/execution_context.py", line 53, in evaluate
    handle = await self.evaluateHandle(
  File "/home/ma/.local/lib/python3.8/site-packages/pyppeteer/execution_context.py", line 92, in evaluateHandle
    raise ElementHandleError(
pyppeteer.errors.ElementHandleError: Evaluation failed: TypeError: Cannot read property 'scrollIntoView' of null
    at __pyppeteer_evaluation_script__:3:21
📈 Getting trending EN:   0%| `

**Comment by quintendewilde** [comment]
Same here!

**Comment by Mr-ZNN** [comment]
Same here!

**Comment by ezzcodeezzlife** [comment]
Same here!
