### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ITzMirko** [sudoguy/tiktokpy#160]
kts@HP-Laptop:~/Scrivania$ python3 TikTok.py 
2021-04-25 10:29:41 | INFO | 🥳 TikTokPy initialized. Version: 0.8.9
2021-04-25 10:29:41 | INFO | 🔧 Settings successfully loaded
2021-04-25 10:29:41 | INFO | 🛑 Cookies not found, anonymous mode
2021-04-25 10:29:41 | INFO | 📈 Getting trending items
📈 Getting trending EN:   0%|                                                                                                                                            | 0/5 [00:00<?, ?it/s]2021-04-25 10:29:47 | INFO | ✋ TikTokPy finished working. Session lasted: 6 seconds
Traceback (most recent call last):
  File "TikTok.py", line 37, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "TikTok.py", line 8, in main
    trending_items = await bot.trending(amount=5)
  File "/home/kts/.local/lib/python3.8/site-packages/tiktokpy/bot/__init__.py", line 57, in trending
    items = await Trending(client=self.client).feed(amount=amount, lang=lang)
  File "/home/kts/.local/lib/python3.8/site-packages/tiktokpy/client/trending.py", line 41, in feed
    await page.evaluate(
  File "/home/kts/.local/lib/python3.8/site-packages/pyppeteer/page.py", line 1184, in evaluate
    return await frame.evaluate(pageFunction, *args, force_expr=force_expr)
  File "/home/kts/.local/lib/python3.8/site-packages/pyppeteer/frame_manager.py", line 308, in evaluate
    return await context.evaluate(
  File "/home/kts/.local/lib/python3.8/site-packages/pyppeteer/execution_context.py", line 53, in evaluate
    handle = await self.evaluateHandle(
  File "/home/kts/.local/lib/python3.8/site-packages/pyppeteer/execution_context.py", line 92, in evaluateHandle
    raise ElementHandleError(
pyppeteer.errors.ElementHandleError: Evaluation failed: TypeError: Cannot read property 'scrollIntoView' of null
    at __pyppeteer_evaluation_script__:3:21
📈 Getting trending EN:   0%|

**Comment by thealphabetguy** [comment]
Is it me or are the people that are getting these errors know nothing about Py and are only here to run scripts to increase there social media views etc.

ITzMirko: The answer is directly in the code.

**Comment by tobeyond** [comment]
ok but can you actually help?
