### ISSUE TITLE
Cant Login

### ISSUE THREAD

**Issue by PascalRse** [sudoguy/tiktokpy#231]
Hello Guys, i cant login , why dont working? Can Please help me

```
C:\Users\Konta\Desktop\TikTokBot\tiktokpy-master>tiktokpy login
Traceback (most recent call last):
  File "C:\Users\Konta\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Konta\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Konta\AppData\Local\Programs\Python\Python310\Scripts\tiktokpy.exe\__main__.py", line 4, in <module>
    from tiktokpy.cli import app
  File "C:\Users\Konta\AppData\Local\Programs\Python\Python310\lib\site-packages\tiktokpy\cli\__init__.py", line 1, in <module>
    import typer
  File "C:\Users\Konta\AppData\Local\Programs\Python\Python310\lib\site-packages\typer\__init__.py", line 12, in <module>
    from click.termui import get_terminal_size as get_terminal_size
ImportError: cannot import name 'get_terminal_size' from 'click.termui' (C:\Users\Konta\AppData\Local\Programs\Python\Python310\lib\site-packages\click\termui.py)
```

**Comment by mikebgrep** [comment]
I login but when i run the bot its say you are not login you can't like unlike etc.
