### ISSUE TITLE
Error like-icon ? Help me

### ISSUE THREAD

**Issue by haind27** [sudoguy/tiktokpy#259]
`
2022-07-22 17:37:06 | INFO | 🧭 Going to @giamcan274's video 7119012120527703323 page for like
2022-07-22 17:37:44 | INFO | ✋ TikTokPy finished working. Session lasted: 57 seconds
Traceback (most recent call last):
  File "/Users/haind/Documents/Working/Project/Tiktok/tiktokpy/quickstart.py", line 37, in <module>
    asyncio.run(main())
  File "/usr/local/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/haind/Documents/Working/Project/Tiktok/tiktokpy/quickstart.py", line 13, in main
    await bot.like(item)
  File "/Users/haind/Documents/Working/Project/Tiktok/tiktokpy/tiktokpy/bot/__init__.py", line 92, in like
    await User(client=self.client).like(
  File "/Users/haind/Documents/Working/Project/Tiktok/tiktokpy/tiktokpy/client/user.py", line 57, in like
    await page.click(like_selector)
  File "/usr/local/lib/python3.9/site-packages/playwright/async_api/_generated.py", line 7983, in click
    await self._impl_obj.click(
  File "/usr/local/lib/python3.9/site-packages/playwright/_impl/_page.py", line 691, in click
    return await self._main_frame.click(**locals_to_params(locals()))
  File "/usr/local/lib/python3.9/site-packages/playwright/_impl/_frame.py", line 474, in click
    await self._channel.send("click", locals_to_params(locals()))
  File "/usr/local/lib/python3.9/site-packages/playwright/_impl/_connection.py", line 43, in send
    return await self._connection.wrap_api_call(
  File "/usr/local/lib/python3.9/site-packages/playwright/_impl/_connection.py", line 369, in wrap_api_call
    return await cb()
  File "/usr/local/lib/python3.9/site-packages/playwright/_impl/_connection.py", line 78, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for selector "div[data-e2e="recommend-list-item-container"]:first-child span[data-e2e="like-icon"]"
`

**Comment by muhammedaksam** [comment]
I think you can see this https://github.com/sudoguy/tiktokpy/pull/256/commits/390dab35c9d6f0e38c9f3fe4afdb698393a884b0

**Comment by haind27** [comment]
> I think you can see this [390dab3](https://github.com/sudoguy/tiktokpy/commit/390dab35c9d6f0e38c9f3fe4afdb698393a884b0)

thank sir. this is solved.
