### ISSUE TITLE
Looks like Playwright was just installed or updated.

### ISSUE THREAD

**Issue by jannikb16** [sudoguy/tiktokpy#272]
After using this Tutorial (https://my-tailwind-nextjs-starter-blog.vercel.app/blog/how-to-use-tiktokpy-for-beginner-programmers-indepth-guide) i got this error: 

C:\Users\baeck\Downloads\tiktokpy>python3 quicklogin.py
2022-09-07 14:32:49 | INFO | 🥳 TikTokPy initialized. Version: 0.9.0
2022-09-07 14:32:49 | INFO | 🔧 Settings successfully loaded
2022-09-07 14:32:49 | INFO | 🛑 Cookies not found, anonymous mode
Traceback (most recent call last):
  File "C:\Users\baeck\Downloads\tiktokpy\quicklogin.py", line 9, in <module>
    asyncio.run(main())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2032.0_x64__qbz5n2kfra8p0\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2032.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "C:\Users\baeck\Downloads\tiktokpy\quicklogin.py", line 5, in main
    async with TikTokPy() as bot:
  File "C:\Users\baeck\Downloads\tiktokpy\tiktokpy\bot\__init__.py", line 43, in __aenter__
    await self.init_bot()
  File "C:\Users\baeck\Downloads\tiktokpy\tiktokpy\bot\__init__.py", line 123, in init_bot
    self.client: Client = await Client.create(headless=self.headless)
  File "C:\Users\baeck\Downloads\tiktokpy\tiktokpy\client\__init__.py", line 104, in create
    await self.init_browser(headless=headless)
  File "C:\Users\baeck\Downloads\tiktokpy\tiktokpy\client\__init__.py", line 38, in init_browser
    self.browser: Browser = await self.playwright.chromium.launch(**params)
  File "C:\Users\baeck\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\playwright\async_api\_generated.py", line 11650, in launch
    await self._impl_obj.launch(
  File "C:\Users\baeck\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\playwright\_impl\_browser_type.py", line 93, in launch
    Browser, from_channel(await self._channel.send("launch", params))
  File "C:\Users\baeck\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\playwright\_impl\_connection.py", line 43, in send
    return await self._connection.wrap_api_call(
  File "C:\Users\baeck\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\playwright\_impl\_connection.py", line 387, in wrap_api_call
    return await cb()
  File "C:\Users\baeck\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\playwright\_impl\_connection.py", line 78, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: Executable doesn't exist at C:\Users\baeck\AppData\Local\ms-playwright\chromium-1019\chrome-win\chrome.exe
╔════════════════════════════════════════════════════════════╗
║ Looks like Playwright was just installed or updated.       ║
║ Please run the following command to download new browsers: ║
║                                                            ║
║     playwright install                                     ║
║                                                            ║
║ <3 Playwright Team                                         ║
╚════════════════════════════════════════════════════════════╝
Exception ignored in: <function BaseSubprocessTransport.__del__ at 0x0000013113CFAB00>
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2032.0_x64__qbz5n2kfra8p0\lib\asyncio\base_subprocess.py", line 126, in __del__
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2032.0_x64__qbz5n2kfra8p0\lib\asyncio\base_subprocess.py", line 104, in close
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2032.0_x64__qbz5n2kfra8p0\lib\asyncio\proactor_events.py", line 108, in close
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2032.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 750, in call_soon
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2032.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 515, in _check_closed
RuntimeError: Event loop is closed

C:\Users\baeck\Downloads\tiktokpy>

**Comment by HoangMoli** [comment]
Dude it literally says that you should run "playwright install", read it man ...
