### ISSUE TITLE
playwright._impl._errors.TimeoutError: Timeout 30000ms exceeded.

### ISSUE THREAD

**Issue by TuanTool** [sudoguy/tiktokpy#340]
I don't know what happenning when I'm running
2023-11-25 22:06:21 | INFO | 🥳 TikTokPy initialized. Version: 0.9.4
2023-11-25 22:06:21 | INFO | 🔧 Settings successfully loaded
2023-11-25 22:06:21 | INFO | 🛑 Cookies not found, anonymous mode
2023-11-25 22:06:22 | INFO | 📈 Getting trending items
2023-11-25 22:06:54 | INFO | ✋ TikTokPy finished working. Session lasted: 32 seconds
Traceback (most recent call last):
  File "D:\Bot_Tiktok\tiktokpy-master\quickstart.py", line 37, in <module>
    asyncio.run(main())
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 664, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "D:\Bot_Tiktok\tiktokpy-master\quickstart.py", line 9, in main
    trending_items = await bot.trending(amount=5)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Bot_Tiktok\tiktokpy-master\tiktokpy\bot\__init__.py", line 79, in trending
    items = await Trending(client=self.client).feed(amount=amount)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Bot_Tiktok\tiktokpy-master\tiktokpy\client\trending.py", line 33, in feed
    _ = await self.client.goto(
        ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Bot_Tiktok\tiktokpy-master\tiktokpy\client\__init__.py", line 102, in goto
    response = await page.goto(full_url, *args, wait_until=wait_until, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\playwright\async_api\_generated.py", line 9260, in goto
    await self._impl_obj.goto(
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\playwright\_impl\_page.py", line 475, in goto
    return await self._main_frame.goto(**locals_to_params(locals()))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\playwright\_impl\_frame.py", line 139, in goto
    await self._channel.send("goto", locals_to_params(locals()))
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\playwright\_impl\_connection.py", line 62, in send
    return await self._connection.wrap_api_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\playwright\_impl\_connection.py", line 492, in wrap_api_call
    return await cb()
           ^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\playwright\_impl\_connection.py", line 100, in inner_send
    result = next(iter(done)).result()
             ^^^^^^^^^^^^^^^^^^^^^^^^^
playwright._impl._errors.TimeoutError: Timeout 30000ms exceeded.

**Comment by AlgorithmAlchemy** [comment]
+++ i have this error

**Comment by guowei3399** [comment]
me too

**Comment by robertonscjr** [comment]
A workaround that worked here was to change `tiktokpy\client_init_.py", line 102` and add `timeout=0` as an argument of `page.goto` call: `response = await page.goto(full_url, timeout=0, *args, wait_until=wait_until, **kwargs)`.
