### ISSUE TITLE
Traceback (most recent call last):

### ISSUE THREAD

**Issue by xifanezz** [sudoguy/tiktokpy#342]
I face this issue when I start it:

📈 Getting trending items
📈 Getting trending en: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:00<00:00, 999.98it/s]
2024-05-25 01:57:57 | INFO | 📹 Found 5 videos
2024-05-25 01:57:58 | INFO | ✋ TikTokPy finished working. Session lasted: 12 seconds
Traceback (most recent call last):
  File "C:\Users\xFaneZz\Desktop\New folder (2)\tiktokpy-master\quickstart.py", line 37, in <module>
    asyncio.run(main())
  File "C:\Python312\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\xFaneZz\Desktop\New folder (2)\tiktokpy-master\quickstart.py", line 9, in main
    trending_items = await bot.trending(amount=5)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xFaneZz\Desktop\New folder (2)\tiktokpy-master\tiktokpy\bot\__init__.py", line 82, in trending
    _trending = FeedItems(__root__=items)
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\pydantic\main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 2 validation errors for FeedItems
__root__ -> 3 -> author -> avatarLarger
  ensure this value has at least 1 characters (type=value_error.any_str.min_length; limit_value=1)
__root__ -> 3 -> author -> verified
  field required (type=value_error.missing)

**Comment by DerekDM15** [comment]
did u find a fix ?

**Comment by xifanezz** [comment]
Yes, thanks

**Comment by DerekDM15** [comment]
How did you do it ?

I am getting this error.
pydantic.error_wrappers.ValidationError: 1 validation error for FeedItems
__root__ -> 3 -> author -> verified
  field required (type=value_error.missing)

**Comment by xifanezz** [comment]
Sorry I thought different email, this tiktokpy is scam don’t bother looking
on to it

**Comment by DerekDM15** [comment]
oh okay thank you

**Comment by DerekDM15** [comment]
did you find any alternatives toa this though ?
