### ISSUE TITLE
[RuntimeError] Bot wont work, 

### ISSUE THREAD

**Issue by nobu333** [sudoguy/tiktokpy#38]
2020-08-15 12:49:59 | INFO | ✅ Used cookies of @SomeRandomGuy
2020-08-15 12:50:36 | INFO | ✋ TikTokPy finished working. Session lasted: 36 seconds
Traceback (most recent call last):
  File "c:\users\SomeRandomGuy\appdata\local\programs\python\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\SomeRandomGuy\appdata\local\programs\python\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\SomeRandomGuy\AppData\Local\Programs\Python\Python38\Scripts\tiktokpy.exe\__main__.py", line 7, in <module>
  File "c:\users\SomeRandomGuy\appdata\local\programs\python\python38\lib\site-packages\typer\main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "c:\users\SomeRandomGuy\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\SomeRandomGuy\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "c:\users\SomeRandomGuy\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\SomeRandomGuy\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\SomeRandomGuy\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\users\SomeRandomGuy\appdata\local\programs\python\python38\lib\site-packages\typer\main.py", line 497, in wrapper
    return callback(**use_params)  # type: ignore
  File "c:\users\SomeRandomGuy\appdata\local\programs\python\python38\lib\site-packages\tiktokpy\cli\utils.py", line 8, in wrapper
    return asyncio.run(f(*args, **kwargs))
  File "c:\users\SomeRandomGuy\appdata\local\programs\python\python38\lib\asyncio\runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "c:\users\SomeRandomGuy\appdata\local\programs\python\python38\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "c:\users\SomeRandomGuy\appdata\local\programs\python\python38\lib\site-packages\tiktokpy\cli\__init__.py", line 13, in login
    await bot.login_session()
  File "c:\users\SomeRandomGuy\appdata\local\programs\python\python38\lib\site-packages\tiktokpy\bot\__init__.py", line 83, in login_session
    await Login().manual_login()
  File "c:\users\SomeRandomGuy\appdata\local\programs\python\python38\lib\site-packages\tiktokpy\client\login.py", line 21, in manual_login
    await page.waitFor(".profile-actions > li:first-child")
  File "c:\users\SomeRandomGuy\appdata\local\programs\python\python38\lib\site-packages\pyppeteer\frame_manager.py", line 855, in __await__
    raise result
pyppeteer.errors.TimeoutError: Waiting for selector ".profile-actions > li:first-child" failed: timeout 30000ms exceeds.
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "c:\users\SomeRandomGuy\appdata\local\programs\python\python38\lib\site-packages\pyppeteer\launcher.py", line 151, in _close_process
    self._loop.run_until_complete(self.killChrome())
  File "c:\users\SomeRandomGuy\appdata\local\programs\python\python38\lib\asyncio\base_events.py", line 591, in run_until_complete
    self._check_closed()
  File "c:\users\SomeRandomGuy\appdata\local\programs\python\python38\lib\asyncio\base_events.py", line 508, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
sys:1: RuntimeWarning: coroutine 'Launcher.killChrome' was never awaited
RuntimeWarning: Enable tracemalloc to get the object allocation traceback

C:\Users\SomeRandomGuy\Desktop\TikTok\tiktokpy-master>

**Comment by sudoguy** [comment]
Bug with manual login was fixed in version 0.8.5. Update package, pls and try again
```bash
pip install -U tiktokpy
```
