### ISSUE TITLE
tiktokpy login fails RuntimeError: Event loop is closed

### ISSUE THREAD

**Issue by elblogbruno** [sudoguy/tiktokpy#64]
When I type tiktokpy login and log in tiktok website I do get this error. I see that the opened browser is trying to access the profile and it displays error loading on tiktok website, maybe it is related?
```
C:\Users\elblo\Desktop>tiktokpy login
2020-09-06 13:54:45 | INFO | 🥳 TikTokPy initialized. Version: 0.8.6
2020-09-06 13:54:46 | INFO | 🔧 Settings successfully loaded
2020-09-06 13:54:46 | INFO | 🛑 Cookies not found, anonymous mode
2020-09-06 13:54:50 | INFO | ✋ TikTokPy finished working. Session lasted: 4 seconds
Traceback (most recent call last):
  File "c:\users\elblo\appdata\local\programs\python\python38-32\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\elblo\appdata\local\programs\python\python38-32\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\elblo\AppData\Local\Programs\Python\Python38-32\Scripts\tiktokpy.exe\__main__.py", line 7, in <module>
  File "c:\users\elblo\appdata\local\programs\python\python38-32\lib\site-packages\typer\main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "c:\users\elblo\appdata\local\programs\python\python38-32\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\elblo\appdata\local\programs\python\python38-32\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "c:\users\elblo\appdata\local\programs\python\python38-32\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\elblo\appdata\local\programs\python\python38-32\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\elblo\appdata\local\programs\python\python38-32\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\users\elblo\appdata\local\programs\python\python38-32\lib\site-packages\typer\main.py", line 497, in wrapper
    return callback(**use_params)  # type: ignore
  File "c:\users\elblo\appdata\local\programs\python\python38-32\lib\site-packages\tiktokpy\cli\utils.py", line 8, in wrapper
    return asyncio.run(f(*args, **kwargs))
  File "c:\users\elblo\appdata\local\programs\python\python38-32\lib\asyncio\runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "c:\users\elblo\appdata\local\programs\python\python38-32\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "c:\users\elblo\appdata\local\programs\python\python38-32\lib\site-packages\tiktokpy\cli\__init__.py", line 13, in login
    await bot.login_session()
  File "c:\users\elblo\appdata\local\programs\python\python38-32\lib\site-packages\tiktokpy\bot\__init__.py", line 85, in login_session
    await Login().manual_login()
  File "c:\users\elblo\appdata\local\programs\python\python38-32\lib\site-packages\tiktokpy\client\login.py", line 18, in manual_login
    await page.waitForSelector(".profile", options={"timeout": 0})
  File "c:\users\elblo\appdata\local\programs\python\python38-32\lib\site-packages\pyppeteer\frame_manager.py", line 853, in __await__
    result = yield from self.promise
  File "c:\users\elblo\appdata\local\programs\python\python38-32\lib\site-packages\pyppeteer\frame_manager.py", line 875, in rerun
    success = await context.evaluateHandle(
  File "c:\users\elblo\appdata\local\programs\python\python38-32\lib\site-packages\pyppeteer\execution_context.py", line 108, in evaluateHandle
    _rewriteError(e)
  File "c:\users\elblo\appdata\local\programs\python\python38-32\lib\site-packages\pyppeteer\execution_context.py", line 238, in _rewriteError
    raise error
  File "c:\users\elblo\appdata\local\programs\python\python38-32\lib\site-packages\pyppeteer\execution_context.py", line 99, in evaluateHandle
    _obj = await self._client.send('Runtime.callFunctionOn', {
pyppeteer.errors.NetworkError: Protocol error Runtime.callFunctionOn: Target closed.
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "c:\users\elblo\appdata\local\programs\python\python38-32\lib\site-packages\pyppeteer\launcher.py", line 151, in _close_process
    self._loop.run_until_complete(self.killChrome())
  File "c:\users\elblo\appdata\local\programs\python\python38-32\lib\asyncio\base_events.py", line 591, in run_until_complete
    self._check_closed()
  File "c:\users\elblo\appdata\local\programs\python\python38-32\lib\asyncio\base_events.py", line 508, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
sys:1: RuntimeWarning: coroutine 'Launcher.killChrome' was never awaited
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
```

**Comment by elblogbruno** [comment]
Interestingly running from visual studio code from cloning this project, worked but is not optimal as on any update of the library i will need to git pull.
